package com.ponykamni.astronomy.data.dto

internal data class AutogeneratedDistanceDataDto(
    private val `data`: Data
) {

    fun getDistance(planetId: String): Long =
        data
            .table
            .rows
            .find { it.entry.id == planetId }
            ?.cells
            ?.find { it.id == planetId }
            ?.distance
            ?.fromEarth
            ?.km
            ?.toDouble()
            ?.toLong()
            ?: 0

    internal data class Data(
        val dates: Dates,
        val observer: Observer,
        val table: Table
    ) {
        internal data class Dates(
            val from: String,
            val to: String
        )

        internal data class Observer(
            val location: Location
        ) {
            internal data class Location(
                val elevation: Int,
                val latitude: Double,
                val longitude: Double
            )
        }

        internal data class Table(
            val header: List<String>,
            val rows: List<Row>
        ) {
            internal data class Row(
                val cells: List<Cell>,
                val entry: Entry
            ) {
                internal data class Cell(
                    val date: String,
                    val distance: Distance,
                    val extraInfo: ExtraInfo,
                    val id: String,
                    val name: String,
                    val position: Position
                ) {
                    internal data class Distance(
                        val fromEarth: FromEarth
                    ) {
                        internal data class FromEarth(
                            val au: String,
                            val km: String
                        )
                    }

                    internal data class ExtraInfo(
                        val elongation: Double,
                        val magnitude: Double
                    )

                    internal data class Position(
                        val constellation: Constellation,
                        val equatorial: Equatorial,
                        val horizonal: Horizonal,
                        val horizontal: Horizontal
                    ) {
                        internal data class Constellation(
                            val id: String,
                            val name: String,
                            val short: String
                        )

                        internal data class Equatorial(
                            val declination: Declination,
                            val rightAscension: RightAscension
                        ) {
                            internal data class Declination(
                                val degrees: String,
                                val string: String
                            )

                            internal data class RightAscension(
                                val hours: String,
                                val string: String
                            )
                        }

                        internal data class Horizonal(
                            val altitude: Altitude,
                            val azimuth: Azimuth
                        ) {
                            internal data class Altitude(
                                val degrees: String,
                                val string: String
                            )

                            internal data class Azimuth(
                                val degrees: String,
                                val string: String
                            )
                        }

                        internal data class Horizontal(
                            val altitude: Altitude,
                            val azimuth: Azimuth
                        ) {
                            internal data class Altitude(
                                val degrees: String,
                                val string: String
                            )

                            internal data class Azimuth(
                                val degrees: String,
                                val string: String
                            )
                        }
                    }
                }

                internal data class Entry(
                    val id: String,
                    val name: String
                )
            }
        }
    }
}