package com.ponykamni.astronomy.data.source

import com.ponykamni.astronomy.data.dto.AutogeneratedDistanceDataDto
import com.ponykamni.astronomy.data.dto.ObserverDto
import com.ponykamni.astronomy.data.network.AstronomyApi
import javax.inject.Inject

internal class NetworkDataSource @Inject constructor(
    private val astronomyApi: AstronomyApi,
) {

    suspend fun getPlanetInfo(planetId: String): AutogeneratedDistanceDataDto {
        val observer = ObserverDto.getObserverForTime(System.currentTimeMillis())

        return astronomyApi.getPlanetPosition(
            planet = planetId,
            latitude = observer.latitude.toString(),
            longitude = observer.longitude.toString(),
            elevation = observer.elevation.toString(),
            fromDate = observer.fromDate,
            toDate = observer.toDate,
            time = observer.time,
        )
    }
}